apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  labels:
    retail-store-sample: secrets-spread
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "Y2F0YWxvZw=="
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "VUQwN3hiTGt0Z093dlhKMg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
  labels:
    retail-store-sample: secrets-spread
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  labels:
    retail-store-sample: secrets-spread
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "RVFhYmFHU0dsdzJlTDVzaA=="
